name: dev
channels:
  - defaults
dependencies:
  - python=3.12
  - scikit-learn
  - pip
  - pip:
      - black
      - isort
      - jupyterlab
      - matplotlib
      - notebook
      - opencv-python
      - pandas
      - playwright
